# Jasypt 加密
JASYPT_BASEURL: ENC(l+Z/1gj7JlP9l4WN12RN0qr6nWOxQ0xl)
JASYPT_USERNAME: ENC(Eq4WR2jwtM4DIKg9gA8kLQ==)
JASYPT_PASSWORD: ENC(zrbh/kdig8bYqHVqEESVzBOp6/amsZ02)

# 中间件端口配置
MYSQL_PORT: 3306
REDIS_PORT: 6379
MINIO_PORT: 9001

# RSA 公钥、私钥配置
RSA_PUBLIC_KEY: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCAm6P6NsqeTZlmpuiTEIBdI2Amp8/M4MWlAQKFsKgU70SI4uYcy09QxnY9j1pOneIA8Zx2on2k3fcwULZ7FL2IuvmYfHhe+sMQQ9RuL1pwjqThhpaorn2XIAZe0NFkzERjMlfb8WYByQWSi43aWV43Ib6uU5+8rNT9UDnV22W/pQIDAQAB
RSA_PRIVATE_KEY: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAICbo/o2yp5NmWam6JMQgF0jYCanz8zgxaUBAoWwqBTvRIji5hzLT1DGdj2PWk6d4gDxnHaifaTd9zBQtnsUvYi6+Zh8eF76wxBD1G4vWnCOpOGGlqiufZcgBl7Q0WTMRGMyV9vxZgHJBZKLjdpZXjchvq5Tn7ys1P1QOdXbZb+lAgMBAAECgYAuyfEPYA25KBwuJ30nu/IncG5Tweus6v2c+VAUmV+dNitl7b6wLRtvFLUB0nyVa4VEuKIm2xkA+SwsLMEm6DXH25XHgEREAzfStL4AgKZ6q3+4PnXccKZ2QjuLnbSiW1o48mY26hoy9bxv1kFwWdeq4SNt6Vv/c1zZxq4yXG4JRQJBAMBZFnOiKAeDN9OuxzCxymqbyh2Q3gdL2+N7P6RfmaLuUATcLE5bogKRHmY2E67w4ZASLxF3F4s1hvc24ikFraMCQQCrKsQhYkOKFUvB0KrHI3GKeN2JUW8l0MyyrwcRCo6+u+lGjVWNBJYVSq5VG8APPFWBtyiHKnNtJJ6w9/I4FqIXAkEAom9Zj4NkTJvanHBgFNY/+3He6ML7TawZYO0nXLfDNh4NA12wKOgnVAWbZ3PJgZY41oMUrqok/tHQTZtSuJPsAwJAbMhSO/FKgVCFhBkM4GDLQTkNer8Rh5QK9Ci+sfrmu5uLZzZdv7DBfain4Rkw1739jeIM1NKK5zuVy1zZSQJBYwJBAJaDKhxvWc5rT3bC4SpJCewVfQ7ou5L6tj0uFWD6OFgETz4KMMWN0mGk1PXrDe58ci3q4vEl+Y8IkOT40r6o6Jc=

server:
  port: 8080
  servlet:
    context-path: /bilibili-api

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${JASYPT_BASEURL}:${MYSQL_PORT}/bilibili-server?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${JASYPT_USERNAME}
    password: ${JASYPT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis 配置
  redis:
    # 地址
    host: ${JASYPT_BASEURL}
    # 端口，默认为 6379
    port: ${REDIS_PORT}
    # 数据库索引
    database: 0
    # 密码
    password: ${JASYPT_PASSWORD}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # 限制文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*-mapper.xml

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从 cookie 中读取 token
  is-read-cookie: false

#minio配置
minio:
  url: http://${JASYPT_BASEURL}:${MINIO_PORT}  #对象存储服务的 URL
  accessKey: ${JASYPT_USERNAME} #Access key账户
  secretKey: ${JASYPT_PASSWORD}  #Secret key密码